### ISSUE TITLE
Runtime Error for a pre-trained model

### ISSUE THREAD

**Issue by xaCheng1996** [KID-7391/seeking-the-shape-of-sound#3]
It seems like the pre-trained model 'backbone_ir50_ms1m_epoch120.pth' in Google drive and BaiduYun are corrupted. I have downloaded this model and put it in ./pretrained_models, and get the following error:

  File "/opt/anaconda3/envs/torch_cv/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/envs/torch_cv/lib/python3.9/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 29047829 more bytes. The file might be corrupted.

It may be an error when uploading the model. Could you check it?

**Comment by KID-7391** [comment]
Hi, thanks for your interest!

I downloaded the checkpoint from google drive and it seems fine. I think some errors might occur when during the download. 
Could you please check the md5 code of the downloaded checkpoint? It should be 8a7cc79a313616c5935ae564f5c93c96.
