### ISSUE TITLE
The pretrained model for evalutaion error

### ISSUE THREAD

**Issue by Zhengyan-Sheng** [KID-7391/seeking-the-shape-of-sound#4]
After download pretrained model for evalution,but the tar file cannot be unzip

**Comment by KID-7391** [comment]
Hi, thanks for your interest!

The pretrained model can be directly loaded without unzipping. See the last line in [config/train_main.yaml](https://github.com/KID-7391/seeking-the-shape-of-sound/blob/master/config/train_main.yaml).
